[template.environment]
  CL_CLIENT_ID="FUu0NX2nYVBKM9i7ZNwSO0gjp8_9Jc6rQqq93erpc3Q"
  CL_ENDPOINT="https://metal-chronometrie-sa.commercelayer.io"

  NEXT_PUBLIC_SANITY_PROJECT_ID="h96zatry"
  NEXT_PUBLIC_SANITY_DATASET="production"
  NEXT_PUBLIC_SANITY_API_VERSION="2022-10-25"
  NEXT_PUBLIC_SANITY_TOKEN="skMu4fBI1RYtAwktZLXEftALsmbGczSaSP7jrXuYOMNz1s8LcJo2Sl7hvymGLFAY9elehuIFlzertBOu7u66r8kq0gNtDg0H1xE99Dnjjm4uRSzU0Lri7qAfmToHZrGyxuYA6C49ot6rIlNG9t8YbFjCsSpwMweKXtsWaBbtYXyjpCoLveLq"

  NEXT_PUBLIC_SANITY_PROJECT_TITLE="brown-jackal"
  NEXT_PUBLIC_SITE_NAME="Optional name for the <title> head tag (you can also edit this directly in the code)."
  NEXT_PUBLIC_SITE_URL="https://metalch.netlify.app/"



